---
- name: Test az graph in Custom EE
  hosts: all

  tasks:
    - name: Query sub id and resource group
      command: /bin/sh -c 'az graph query --help'
      register: graph_result

    - name: Display graph query result
      debug:
        var: graph_result.stdout

