---
- name: Test az graph in Custom EE
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3 

  tasks:
    - name: Disable Python user site-packages for Ansible
      ansible.builtin.command: "python3 -s -m site"

    - name: lets check az version
      command: /bin/sh -c 'az version'
      register: az_version

    - name: Display az version
      debug:
        var: az_version.stdout

    - name: reinstall resource-graph
      command: /bin/sh -c 'az extension add -n resource-graph -y --debug'

    - name: Query sub id and resource group
      command: /bin/sh -c 'PYTHONNOUSERSITE=1 /usr/bin/az graph query --help'
      register: graph_result

    - name: Display graph query result
      debug:
        var: graph_result.stdout
